/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VietgapRouteImport } from './routes/vietgap'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as RewardRouteImport } from './routes/reward'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HrRouteImport } from './routes/hr'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as AttendanceManagementRouteImport } from './routes/attendance-management'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingCourseIdRouteImport } from './routes/training.$courseId'
import { Route as DetailsModuleIdRouteImport } from './routes/details.$module.$id'

const VietgapRoute = VietgapRouteImport.update({
  id: '/vietgap',
  path: '/vietgap',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardRoute = RewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceManagementRoute = AttendanceManagementRouteImport.update({
  id: '/attendance-management',
  path: '/attendance-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingCourseIdRoute = TrainingCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => TrainingRoute,
} as any)
const DetailsModuleIdRoute = DetailsModuleIdRouteImport.update({
  id: '/details/$module/$id',
  path: '/details/$module/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/attendance': typeof AttendanceRoute
  '/attendance-management': typeof AttendanceManagementRoute
  '/certifications': typeof CertificationsRoute
  '/chat': typeof ChatRoute
  '/contracts': typeof ContractsRoute
  '/hr': typeof HrRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/register': typeof RegisterRoute
  '/reward': typeof RewardRoute
  '/science': typeof ScienceRoute
  '/setup': typeof SetupRoute
  '/training': typeof TrainingRouteWithChildren
  '/users': typeof UsersRoute
  '/vietgap': typeof VietgapRoute
  '/training/$courseId': typeof TrainingCourseIdRoute
  '/details/$module/$id': typeof DetailsModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/attendance': typeof AttendanceRoute
  '/attendance-management': typeof AttendanceManagementRoute
  '/certifications': typeof CertificationsRoute
  '/chat': typeof ChatRoute
  '/contracts': typeof ContractsRoute
  '/hr': typeof HrRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/register': typeof RegisterRoute
  '/reward': typeof RewardRoute
  '/science': typeof ScienceRoute
  '/setup': typeof SetupRoute
  '/training': typeof TrainingRouteWithChildren
  '/users': typeof UsersRoute
  '/vietgap': typeof VietgapRoute
  '/training/$courseId': typeof TrainingCourseIdRoute
  '/details/$module/$id': typeof DetailsModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/attendance': typeof AttendanceRoute
  '/attendance-management': typeof AttendanceManagementRoute
  '/certifications': typeof CertificationsRoute
  '/chat': typeof ChatRoute
  '/contracts': typeof ContractsRoute
  '/hr': typeof HrRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/register': typeof RegisterRoute
  '/reward': typeof RewardRoute
  '/science': typeof ScienceRoute
  '/setup': typeof SetupRoute
  '/training': typeof TrainingRouteWithChildren
  '/users': typeof UsersRoute
  '/vietgap': typeof VietgapRoute
  '/training/$courseId': typeof TrainingCourseIdRoute
  '/details/$module/$id': typeof DetailsModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/404'
    | '/attendance'
    | '/attendance-management'
    | '/certifications'
    | '/chat'
    | '/contracts'
    | '/hr'
    | '/legal'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/projects'
    | '/quotations'
    | '/register'
    | '/reward'
    | '/science'
    | '/setup'
    | '/training'
    | '/users'
    | '/vietgap'
    | '/training/$courseId'
    | '/details/$module/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/attendance'
    | '/attendance-management'
    | '/certifications'
    | '/chat'
    | '/contracts'
    | '/hr'
    | '/legal'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/projects'
    | '/quotations'
    | '/register'
    | '/reward'
    | '/science'
    | '/setup'
    | '/training'
    | '/users'
    | '/vietgap'
    | '/training/$courseId'
    | '/details/$module/$id'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/404'
    | '/attendance'
    | '/attendance-management'
    | '/certifications'
    | '/chat'
    | '/contracts'
    | '/hr'
    | '/legal'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/projects'
    | '/quotations'
    | '/register'
    | '/reward'
    | '/science'
    | '/setup'
    | '/training'
    | '/users'
    | '/vietgap'
    | '/training/$courseId'
    | '/details/$module/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  AttendanceRoute: typeof AttendanceRoute
  AttendanceManagementRoute: typeof AttendanceManagementRoute
  CertificationsRoute: typeof CertificationsRoute
  ChatRoute: typeof ChatRoute
  ContractsRoute: typeof ContractsRoute
  HrRoute: typeof HrRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  QuotationsRoute: typeof QuotationsRoute
  RegisterRoute: typeof RegisterRoute
  RewardRoute: typeof RewardRoute
  ScienceRoute: typeof ScienceRoute
  SetupRoute: typeof SetupRoute
  TrainingRoute: typeof TrainingRouteWithChildren
  UsersRoute: typeof UsersRoute
  VietgapRoute: typeof VietgapRoute
  DetailsModuleIdRoute: typeof DetailsModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vietgap': {
      id: '/vietgap'
      path: '/vietgap'
      fullPath: '/vietgap'
      preLoaderRoute: typeof VietgapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reward': {
      id: '/reward'
      path: '/reward'
      fullPath: '/reward'
      preLoaderRoute: typeof RewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-management': {
      id: '/attendance-management'
      path: '/attendance-management'
      fullPath: '/attendance-management'
      preLoaderRoute: typeof AttendanceManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$courseId': {
      id: '/training/$courseId'
      path: '/$courseId'
      fullPath: '/training/$courseId'
      preLoaderRoute: typeof TrainingCourseIdRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/details/$module/$id': {
      id: '/details/$module/$id'
      path: '/details/$module/$id'
      fullPath: '/details/$module/$id'
      preLoaderRoute: typeof DetailsModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrainingRouteChildren {
  TrainingCourseIdRoute: typeof TrainingCourseIdRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingCourseIdRoute: TrainingCourseIdRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R404Route: R404Route,
  AttendanceRoute: AttendanceRoute,
  AttendanceManagementRoute: AttendanceManagementRoute,
  CertificationsRoute: CertificationsRoute,
  ChatRoute: ChatRoute,
  ContractsRoute: ContractsRoute,
  HrRoute: HrRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  QuotationsRoute: QuotationsRoute,
  RegisterRoute: RegisterRoute,
  RewardRoute: RewardRoute,
  ScienceRoute: ScienceRoute,
  SetupRoute: SetupRoute,
  TrainingRoute: TrainingRouteWithChildren,
  UsersRoute: UsersRoute,
  VietgapRoute: VietgapRoute,
  DetailsModuleIdRoute: DetailsModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
