/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as RewardRouteImport } from './routes/reward'
import { Route as QuotationsRouteImport } from './routes/quotations'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as HrRouteImport } from './routes/hr'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingCourseIdRouteImport } from './routes/training.$courseId'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardRoute = RewardRouteImport.update({
  id: '/reward',
  path: '/reward',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotationsRoute = QuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingCourseIdRoute = TrainingCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => TrainingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/chat': typeof ChatRoute
  '/contracts': typeof ContractsRoute
  '/hr': typeof HrRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/reward': typeof RewardRoute
  '/training': typeof TrainingRouteWithChildren
  '/training/$courseId': typeof TrainingCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/chat': typeof ChatRoute
  '/contracts': typeof ContractsRoute
  '/hr': typeof HrRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/reward': typeof RewardRoute
  '/training': typeof TrainingRouteWithChildren
  '/training/$courseId': typeof TrainingCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certifications': typeof CertificationsRoute
  '/chat': typeof ChatRoute
  '/contracts': typeof ContractsRoute
  '/hr': typeof HrRoute
  '/projects': typeof ProjectsRoute
  '/quotations': typeof QuotationsRoute
  '/reward': typeof RewardRoute
  '/training': typeof TrainingRouteWithChildren
  '/training/$courseId': typeof TrainingCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certifications'
    | '/chat'
    | '/contracts'
    | '/hr'
    | '/projects'
    | '/quotations'
    | '/reward'
    | '/training'
    | '/training/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certifications'
    | '/chat'
    | '/contracts'
    | '/hr'
    | '/projects'
    | '/quotations'
    | '/reward'
    | '/training'
    | '/training/$courseId'
  id:
    | '__root__'
    | '/'
    | '/certifications'
    | '/chat'
    | '/contracts'
    | '/hr'
    | '/projects'
    | '/quotations'
    | '/reward'
    | '/training'
    | '/training/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificationsRoute: typeof CertificationsRoute
  ChatRoute: typeof ChatRoute
  ContractsRoute: typeof ContractsRoute
  HrRoute: typeof HrRoute
  ProjectsRoute: typeof ProjectsRoute
  QuotationsRoute: typeof QuotationsRoute
  RewardRoute: typeof RewardRoute
  TrainingRoute: typeof TrainingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reward': {
      id: '/reward'
      path: '/reward'
      fullPath: '/reward'
      preLoaderRoute: typeof RewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotations': {
      id: '/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof QuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$courseId': {
      id: '/training/$courseId'
      path: '/$courseId'
      fullPath: '/training/$courseId'
      preLoaderRoute: typeof TrainingCourseIdRouteImport
      parentRoute: typeof TrainingRoute
    }
  }
}

interface TrainingRouteChildren {
  TrainingCourseIdRoute: typeof TrainingCourseIdRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingCourseIdRoute: TrainingCourseIdRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificationsRoute: CertificationsRoute,
  ChatRoute: ChatRoute,
  ContractsRoute: ContractsRoute,
  HrRoute: HrRoute,
  ProjectsRoute: ProjectsRoute,
  QuotationsRoute: QuotationsRoute,
  RewardRoute: RewardRoute,
  TrainingRoute: TrainingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
